version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/store_db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - store-network

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - store-network

volumes:
  postgres_data:

networks:
  store-network:
    driver: bridge 