[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "yarn start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[deploy.preDeploySteps]]
command = "echo 'Starting Prisma setup...'"

[[deploy.preDeploySteps]]
command = "npx prisma generate"

[[deploy.preDeploySteps]]
command = "npx prisma db push --force-reset"

[[deploy.preDeploySteps]]
command = "npx prisma db seed"

[[deploy.preDeploySteps]]
command = "echo 'Prisma setup completed!'"